batch_size: 22
n_workers: 16
iterations: 20000000
eval_every: 1
accumulate_grad_batches: 1
fp16: False
clip_denoised: True
ema_rate: 0.999

lr: 1e-4
wd: "0"

fine_tune_from: /home/drozdova/projects/ska-project/diffusion-true-ska/lightning_logs/2023-05-31-11-17-27_noisy_from_uv_steps20/version_0/checkpoints/best_epoch=143_step=53856.ckpt
schedule_sampler: uniform

model:
  use_y_conditioning: False
  diffusion_steps: 1000

dataset:
  image_path: /home/drozdova/projects/dataset_ska/real_data/pwv_sims/pwv_0.913/data/
  label_path:
  size: 128
  n_classes: 1400
  n_channels: 1
  from_uv: True
  real_data: True


comment: noisy_from_uv_steps20_pwv_0.913
