batch_size: 32
n_workers: 16
iterations: 200000
eval_every: 1
accumulate_grad_batches: 1
fp16: False

lr: 3e-4
wd: "0"

fine_tune_from:

schedule_sampler: uniform

dataset:
  image_path: /home/kinakh/Datasets/galaxy-zoo/images_training_rev1/
  label_path: /home/kinakh/Datasets/galaxy-zoo/training_solutions_rev1.csv
  size: 64
  n_classes: 37

comment: galaxy_zoo_diffusion_classifier


