accumulate_grad_batches: 1
batch_size: 22
clip_denoised: true
comment: CASA_zero_power10
dataset:
  from_uv: false
  image_path: /Users/mariadrozdova/PycharmProjects/diffusion-for-sources-characterisation/toy_data/
  label_path: null
  n_channels: 1
  n_classes: 1400
  power: 30
  real_data: false
  size: 128
  use_zeros: true
ema_rate: 0.999
eval_every: 1
fine_tune_from: null
fp16: false
iterations: 20000000
lr: 1e-4
model:
  diffusion_steps: 1000
  use_y_conditioning: false
n_workers: 16
schedule_sampler: uniform
wd: '0'
